# Generated by Django 3.1.4 on 2021-06-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='picname',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picname2',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picurl',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picurl2',
        ),
    ]
