# Generated by Django 3.1.4 on 2021-06-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0002_auto_20210608_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='link',
            new_name='lin',
        ),
    ]
