# Generated by Django 3.1.4 on 2021-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0003_auto_20210614_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='abouttxt',
        ),
        migrations.AddField(
            model_name='main',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
