# Generated by Django 3.1.4 on 2021-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0005_auto_20210615_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='lin',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
