# Generated by Django 3.1.4 on 2021-05-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coronamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('detail_description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('N', 'ncr'), ('UP', 'uttar pradesh'), ('B', 'bihar'), ('UK', 'uttarakhand'), ('J', 'jharkhand'), ('R', 'rajasthan'), ('MP', 'madhya pradesh'), ('M', 'maharashtra'), ('H', 'haryana'), ('CH', 'chhattisgarh'), ('HP', 'himachal pradesh')], max_length=2)),
                ('s_image', models.ImageField(upload_to='producting')),
                ('s_vedio', models.FileField(blank=True, upload_to='vedio/%y')),
            ],
        ),
    ]
