# Generated by Django 3.1.4 on 2021-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_statemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('detail_description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('s_image', models.ImageField(blank=True, upload_to='producting')),
                ('s_vedio', models.FileField(blank=True, upload_to='vedio/%y')),
            ],
        ),
    ]
