# Generated by Django 3.1.4 on 2021-05-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='caption',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
