# Generated by Django 3.1.4 on 2021-05-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210517_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermodel',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
