# Generated by Django 3.1.4 on 2021-05-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210517_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplmodel',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
