# Generated by Django 3.1.4 on 2021-05-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210517_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entertainment',
        ),
    ]
