# Generated by Django 3.1.4 on 2021-05-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_entertainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('d_description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('B', 'breaking'), ('L', 'latest')], max_length=2)),
                ('s_image', models.ImageField(blank=True, upload_to='producting')),
                ('s_vedio', models.FileField(blank=True, upload_to='vedio/%y')),
            ],
        ),
    ]
