# Generated by Django 3.1.4 on 2021-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='s_image',
            field=models.ImageField(blank=True, upload_to='producting'),
        ),
    ]
