# Generated by Django 3.1.4 on 2021-06-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactmodel_s_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='s_image',
        ),
    ]
