# Generated by Django 3.1.4 on 2021-06-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_contactmodel_s_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='subject',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
