# Generated by Django 3.1.4 on 2021-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_entertainmentmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentmodel',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
