# Generated by Django 3.1.4 on 2021-06-17 05:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_entertainmentmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='d_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
