# Generated by Django 3.1.4 on 2021-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210617_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentmodel',
            name='a',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
