# Generated by Django 3.1.4 on 2021-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210617_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
