# Generated by Django 3.1.4 on 2021-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210617_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='s_image',
            field=models.ImageField(blank=True, null=True, upload_to='producting'),
        ),
    ]
